MODEL:
  # model type:
  # 'DeepLabV3', 'DeepLabV3Plus', 'FPN', 'Linknet',
  # 'PAN', 'PSPNet', 'Unet', 'UnetPlusPlus'
  TYPE: 'DeepLabV3Plus'
  BACKBONE: 'resnet50'
OUTPUT_DIR: 'results_dl3plus_res50'
