MODEL:
  # model type:
  # 'DeepLabV3', 'DeepLabV3Plus', 'FPN', 'Linknet',
  # 'PAN', 'PSPNet', 'Unet', 'UnetPlusPlus'
  TYPE: 'UnetPlusPlus'
  BACKBONE: 'efficientnet-b4'
OUTPUT_DIR: 'results_upp_effb4'
